### ISSUE TITLE
v0.3.0-alpha3在打开时发生闪退

### ISSUE THREAD

**Issue by zhou1012** [RikkaW/FCM-for-Mojo#20]
使用LOS系统，7.1.2，在打开时闪退，提示需要读取Document文件夹的权限，可是对权限没有丝毫限制

**Comment by RikkaW** [comment]
需要相关 log （

**Comment by haruue** [comment]
``` logcat
08-12 19:10:15.224 18709 18709 W System  : ClassLoader referenced unknown path: /data/app/moe.shizuku.fcmformojo-1/lib/arm
08-12 19:10:15.278 18709 18709 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
08-12 19:10:15.304 18709 18709 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-12 19:10:15.325 18709 18709 I FA      : App measurement is starting up, version: 11020
08-12 19:10:15.325 18709 18709 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-12 19:10:15.336 18709 18709 I FA      : To enable faster debug mode event logging run:
08-12 19:10:15.336 18709 18709 I FA      :   adb shell setprop debug.firebase.analytics.app moe.shizuku.fcmformojo
08-12 19:10:15.348 18709 18709 I FirebaseInitProvider: FirebaseApp initialization successful
08-12 19:10:15.368 18709 18709 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-12 19:10:15.716 18709 18709 D AndroidRuntime: Shutting down VM
08-12 19:10:15.718 18709 18709 E AndroidRuntime: FATAL EXCEPTION: main
08-12 19:10:15.718 18709 18709 E AndroidRuntime: Process: moe.shizuku.fcmformojo, PID: 18709
08-12 19:10:15.718 18709 18709 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{moe.shizuku.fcmformojo/moe.shizuku.fcmformojo.MainActivity}: android.content.res.Resources$NotFoundException: File res/xml/preference.xml from xml type xml resource ID #0x7f110001
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/xml/preference.xml from xml type xml resource ID #0x7f110001
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:990)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2103)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.content.res.Resources.getXml(Resources.java:1164)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at moe.shizuku.preference.h.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at moe.shizuku.preference.i.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at moe.shizuku.preference.f.d(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at moe.shizuku.fcmformojo.c.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at moe.shizuku.preference.f.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.g.l(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.m.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.r.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.r.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.r.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.m.a(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.m.b(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.m.e(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.m.e(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.m.m(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.j.f(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.support.a.a.h.onStart(Unknown Source)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6696)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	... 9 more
08-12 19:10:15.718 18709 18709 E AndroidRuntime: Caused by: java.io.FileNotFoundException: res/xml/preference.xml
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:519)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:975)
08-12 19:10:15.718 18709 18709 E AndroidRuntime: 	... 31 more
```

注意 `Caused by: java.io.FileNotFoundException: res/xml/preference.xml`

**Comment by haruue** [comment]
另外我这边解包不了 [ffm-65.apk](https://github.com/RikkaW/FCM-for-Mojo/releases/download/v0.3.0-alpha3/ffm-65.apk) ，貌似资源确实有问题，Rikka 重新编译一个 release 试试？

**Comment by RikkaW** [comment]
[ffm-67.apk](https://github.com/RikkaW/FCM-for-Mojo/releases/download/v0.3.0-alpha3/ffm-67.apk)
应该好了
（都怪 AS 3.0 beta 1 和 2
