### ISSUE TITLE
Failed to execute node node/index.js

### ISSUE THREAD

**Issue by SingSky** [RikkaW/FCM-for-Mojo#41]
### The error messages are as following:
[root@host server]# node node/index.js

/root/ffmqq/FCM-for-Mojo-0.3.3/server/node/node_modules/http-auth/src/http-auth.js:4
const utils = require('./auth/utils');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/ffmqq/FCM-for-Mojo-0.3.3/server/node/index.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
### My node version:
node --version
v0.10.48

**Comment by haruue** [comment]
`const` is disabled by default in strict mode in nodejs 0.10. 
Maybe you should upgrade your nodejs. Using of obsolete nodejs is not recommended.
The latest nodejs version is v8.4.0.

PS: If you use a vintage Linux distribution such as CentOS or Debian, maybe you should not install nodejs from package manager directly. Please refer to [this manual](https://nodejs.org/en/download/package-manager/) for Installation guide.

**Comment by SingSky** [comment]
@haruue  Thanks for your kindly help! It works perfectly after updating nodejs to v6.11.2, the LTS version. Maybe it's worth mentioning in the install manual to avoid more unnecessary misunderstandings?
