### ISSUE TITLE
get_group_basic_info 出错导致FFM退出

### ISSUE THREAD

**Issue by StringKe** [RikkaW/FCM-for-Mojo#47]
```
[FFM] /openqq/get_group_basic_info
[FFM] exit
[17/09/02 10:48:36] [info] 捕获到停止信号[INT]，准备停止...
[17/09/02 10:48:36] [info] 清除残留的pid文件
[FFM] killing Mojo-Webqq...
/root/serverqq/node/push.js:9
            console.error("[FFM] push failed, error: " + error + " body: " + body + " code: " + response.statusCode);
                                                                                                        ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.callback [as _callback] (/root/serverqq/node/push.js:9:105)
    at self.callback (/root/serverqq/node/node_modules/request/request.js:188:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/root/serverqq/node/node_modules/request/request.js:884:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
```

**Comment by WordlessEcho** [comment]
代码块的格式是头尾各一个 ``` ``` ```

**Comment by StringKe** [comment]
## 这次不是get_group_basic_info了

```
[FFM] /ffm/send
[FFM] exit
[17/09/02 11:19:25] [info] 捕获到停止信号[INT]，准备停止...
[17/09/02 11:19:25] [info] 清除残留的pid文件
[FFM] killing Mojo-Webqq...
/root/serverqq/node/push.js:9
            console.error("[FFM] push failed, error: " + error + " body: " + body + " code: " + response.statusCode);
                                                                                                        ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.callback [as _callback] (/root/serverqq/node/push.js:9:105)
    at self.callback (/root/serverqq/node/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/root/serverqq/node/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
[17/09/02 11:19:25] [warn] http://127.0.0.1:5004/ffm/send 请求(0/1)失败: - Premature connection close
[root@jdu4e00u53f7 serverqq]# [17/09/02 11:19:25] [warn] http://127.0.0.1:5004/ffm/send 请求(1/1)失败: - Connection refused
[17/09/02 11:19:25] [info] 客户端停止运行

```
